module.exports = [
    './gulp/tasks/sass',    
    './gulp/tasks/scripts', 
    './gulp/tasks/copy', 
    './gulp/tasks/copy_php',
    './gulp/tasks/copy_server',
    './gulp/tasks/allcss', 
    './gulp/tasks/clean', 
    './gulp/tasks/images', 
    './gulp/tasks/build', 
    './gulp/tasks/html', 
    './gulp/tasks/allimg', 
    './gulp/tasks/serve', 
    './gulp/tasks/changejs',
];